version: '3.1'
services:
  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - "/dados/Projects/cursos/go-stack/go-barber/backend/db-files:/var/lib/postgresql/data"
